### ISSUE TITLE
Перестала работать интеграция. 

### ISSUE THREAD

**Issue by diemon24** [alryaz/hass-mosoblgaz#11]
Перестала работать интеграция. Никаких изменений/обновлений в ХА не производилось. Выдает ошибку:

Эта ошибка возникла в кастомной интеграции.

Logger: homeassistant.config_entries
Source: custom_components/mosoblgaz/api.py:457 
Integration: Мособлгаз (Mosoblgaz) (documentation, issues) 
First occurred: 02:24:57 (1 occurrences) 
Last logged: 02:24:57

Error setting up entry User: your-email@mail for mosoblgaz
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/mosoblgaz/__init__.py", line 294, in async_setup_entry
    contracts = await api_object.fetch_contracts(with_data=False)
  File "/config/custom_components/mosoblgaz/api.py", line 522, in fetch_contracts
    response_list = await self.perform_queries(
  File "/config/custom_components/mosoblgaz/api.py", line 457, in perform_queries
    return list(map(lambda x: x["data"], json_response))
  File "/config/custom_components/mosoblgaz/api.py", line 457, in <lambda>
    return list(map(lambda x: x["data"], json_response))
KeyError: 'data'

**Comment by diemon24** [comment]
после удаления интеграции, при попытке заново авторизоваться выдает следующие ошибки: 

<img width="854" alt="image" src="https://github.com/alryaz/hass-mosoblgaz/assets/91910101/32e0bf98-3267-4aa5-b91e-9a190905241b">

**Comment by diemon24** [comment]
> Поменялся API; буду смотреть на днях.

Спасибо большое, очень ждем

**Comment by NikitaKorneev** [comment]
Аналогично!
@alryaz искренне спасибо за ваш труд!

**Comment by DaN66O** [comment]
Стоит ждать исправления интеграции ?

**Comment by alryaz** [comment]
@DaN66O отработал нововведения HA на другом компоненте, сейчас в процессе рефакторинга

**Comment by alryaz** [comment]
Исправлено в хотфиксе v1.0.2.

Не отменяет, к сожалению, того, что придётся переделывать компонент с нуля...
