### ISSUE TITLE
Не работает после обновления HA 2023.06

### ISSUE THREAD

**Issue by booroondook-eng** [alryaz/hass-mosoblgaz#12]
Сразу после обновления HA интеграция показала, что все три объекта находятся в недоступном состоянии.
Перезагрузка интеграции не помогла.
После удаления аккаунта повторная регистрация прошла вроде бы нормально, но интеграция теперь не содержит ни одного объекта.
![2023-06-08 21_08_47-Window](https://github.com/alryaz/hass-mosoblgaz/assets/8210458/a153b905-eea8-400c-9d83-09bb205ae816)

**Comment by alryaz** [comment]
Fixed @ v2023.3.0
