### ISSUE TITLE
Не работает на HA 2024.2.3

### ISSUE THREAD

**Issue by booroondook-eng** [alryaz/hass-mosoblgaz#16]
Пишет в логах следующее:
`2024-02-26 07:07:58.822 ERROR (MainThread) [custom_components.mosoblgaz] (user|XXXXXXXXXXXX)Error authenticating: Failed to authenticate: no site key set`

(XXXXXXXXXXXX - номер лицевого счета, он же используется как логин)

Версия интеграции последняя - 2024.2.0

**Comment by rbalaev** [comment]
Испытываю те же проблемы. Но кажется, что автор перестал поддерживать интеграцию.
`Logger: custom_components.mosoblgaz
Source: custom_components/mosoblgaz/__init__.py:297
Integration: Мособлгаз (Mosoblgaz) ([documentation](https://github.com/alryaz/hass-mosoblgaz), [issues](https://github.com/alryaz/hass-mosoblgaz/issues))
First occurred: 24 февраля 2024 г. в 20:46:21 (1772 occurrences)
Last logged: 12:05:06

(user|user@gmail.com)Error authenticating: Failed to authenticate: no site key set`

**Comment by alryaz** [comment]
Версия интеграции какая?

**Comment by rbalaev** [comment]
Откатил на 1.0.3 и все заработало
HA версии 2024.2.2

**Comment by DaN66O** [comment]
Тоже не работает. Интеграция последняя.
Та же самая ошибка.

**Comment by booroondook-eng** [comment]
> Версия интеграции какая?

Последняя - 2024.2.0

**Comment by motogon** [comment]
+1

**Comment by booroondook-eng** [comment]
HA обновился на 2024.2.4, интеграция 2024.2.0 по-прежнему не работает.

**Comment by rbalaev** [comment]
Откатитесь на 1.0 3

**Comment by booroondook-eng** [comment]
> Откатитесь на 1.0 3

Уверены, что заработает на HA 2024.2.4 ?

**Comment by DaN66O** [comment]
> > Откатитесь на 1.0 3
> 
> Уверены, что заработает на HA 2024.2.4 ?

Работает, но с ошибками и предупреждениями в логе.

**Comment by rbalaev** [comment]
> > > Откатитесь на 1.0 3
> > 
> > 
> > Уверены, что заработает на HA 2024.2.4 ?
> 
> Работает, но с ошибками и предупреждениями в логе.

пока это единственный рабочий вариант.

**Comment by logistik777** [comment]
у меня ни на 2.0 ни на 1.03 не работает аутентификация

**Comment by rbalaev** [comment]
@alryaz Добрый день, подскажите, стоит ждать фикса?

**Comment by diemon24** [comment]
Тоже работала интеграция и несколько дней назад перестала. Авторизация не работает

**Comment by rbalaev** [comment]
> Тоже работала интеграция и несколько дней назад перестала. Авторизация не работает

у меня заработала 1.0.3 только когда я авторизацию в конфигурейшене прописал

**Comment by logistik777** [comment]
> > Тоже работала интеграция и несколько дней назад перестала. Авторизация не работает
> 
> у меня заработала 1.0.3 только когда я авторизацию в конфигурейшене прописал

а вот у меня нет! Ждем исправлений от автора

**Comment by diemon24** [comment]
@alryaz подскажите плс, будет ли исправлена авторизация?

**Comment by alryaz** [comment]
1. 

> @alryaz подскажите плс, будет ли исправлена авторизация?

Завтра (10.03.2024) собрался возиться. Будет обновление.

**Comment by diemon24** [comment]
> 1. 
> 
> 
> 
> > @alryaz подскажите плс, будет ли исправлена авторизация?
> 
> 
> 
> Завтра (10.03.2024) собрался возиться. Будет обновление.

Спасибо!!! Ждем...

**Comment by DaN66O** [comment]
> > @alryaz подскажите плс, будет ли исправлена авторизация?
> 
> Завтра (10.03.2024) собрался возиться. Будет обновление.

Есть успехи ? ))

**Comment by alryaz** [comment]
Есть и успехи, и проблемы. На двух учётных записях, что я использую для тестирования, вылетает капча уже целый день. И от теста до теста не легче.

Как стабильно пройдут обновления в течение ещё пары-тройки часов, выложу. Параллельно пробую перенести на reauth.

**Comment by alryaz** [comment]
https://github.com/alryaz/hass-mosoblgaz/releases/tag/v2024.3.0

**Comment by DaN66O** [comment]
Все работает, спасибо.
Осталось предупреждение вылечить.
`VOLUME_CUBIC_METERS was used from mosoblgaz, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfVolume.CUBIC_METERS instead, please create a bug report at https://github.com/alryaz/hass-mosoblgaz/issues`

**Comment by alryaz** [comment]
> Все работает, спасибо. Осталось предупреждение вылечить. `VOLUME_CUBIC_METERS was used from mosoblgaz, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfVolume.CUBIC_METERS instead, please create a bug report at https://github.com/alryaz/hass-mosoblgaz/issues`

@ v2024.3.1
