### ISSUE TITLE
Ввод показаний счетчика 

### ISSUE THREAD

**Issue by conrad66** [alryaz/hass-mosoblgaz#2]
Добрый день.
Газовый счетчик имеет возможность снимать показания.
Есть ли возможность передавать показания счетчика через API в Мособлгаз ?

**Comment by alryaz** [comment]
Нет, такой возможности нет, но могу попробовать добавить при Вашей поддержке в тестировании.

**Comment by fairyfeller** [comment]
Добрый день! Готов поучаствовать в тестировании

**Comment by alryaz** [comment]
@fairyfeller Здравствуйте! Напишите в Telegram: @alryaz

**Comment by alryaz** [comment]
Реализовано в v0.1.3
