### ISSUE TITLE
 [invoice_name] is an invalid option for [mosoblgaz]

### ISSUE THREAD

**Issue by conrad66** [alryaz/hass-mosoblgaz#3]
Конфигурация :
mosoblgaz:
  - username: !secret 1_mosoblgaz_username
    password: !secret 1_mosoblgaz_password
    contract_name: 'MOG Contract 1'
    meter_name: 'MOG Meter 1'
    invoice_name: 'MOG Invoice 1'

  - username: !secret 2_mosoblgaz_username
    password: !secret 2_mosoblgaz_password
    contract_name: 'MOG Contract 2'
    meter_name: 'MOG Meter 2'
    invoice_name: 'MOG Invoice 2'

В чем ошибка ?

p.s. В описании неточность, вместо invoice_name написано meter_name
p.s.s
Складывается впечатление что компонент не дружит с ssdp
в логах такое:
homeassistant/components/ssdp/__init__.py", line 39, in initialize await scanner.async_scan(None)
homeassistant/components/ssdp/__init__.py", line 63, in async_scan await self._process_entries(entries)
homeassistant/components/ssdp/__init__.py", line 87, in _process_entries result for result in await asyncio.gather(*tasks) if result is not None
homeassistant/components/ssdp/__init__.py", line 127, in _process_entry if all(info.get(k) == v for (k, v) in matcher.items()):
AttributeError: 'str' object has no attribute 'items'

Если отключить  ssdp то получаю другую ошибку: 
custom_components/mosoblgaz/sensor.py", line 414, in async_update prefix + 'paid': invoice.paid,
custom_components/mosoblgaz/mosoblgaz.py", line 684, in paid return float(self._data['payment'])
TypeError: float() argument must be a string or a number, not 'NoneType'
ERROR (MainThread) [homeassistant.components.sensor] Platform mosoblgaz does not generate unique IDs. ID invoice_xxxxx

**Comment by alryaz** [comment]
Поправлено в v0.1.0b2
