### ISSUE TITLE
Счетчик газа

### ISSUE THREAD

**Issue by saintman23** [alryaz/hass-mosoblgaz#7]
С версии 2021.09 HA поддерживает новый класс сенсора газа. Для  корректной работы счетчика газа в HA нужно поправить следующее:

    unit_of_measurement: 'm³'  - сейчас русская м
    state_class: 'total_increasing' - здесь не очень понятно, скармливать НА нужно общий счетчик или расход газа за период.
    device_class: 'gas'

Спасибо.

**Comment by alryaz** [comment]
Добавлено в v1.0.0

**Comment by saintman23** [comment]
device_class: mosoblgaz_meter
нужно поменять на 
device_class: gas
иначе HA выдает ошибку при добавлении счетчика в разделе "Конфигурация - Энергия"

**Comment by alryaz** [comment]
Исправлено в v1.0.1
