### ISSUE TITLE
Интеграция не авторизуется в личном кабинете

### ISSUE THREAD

**Issue by booroondook-eng** [alryaz/hass-mosoblgaz#9]
15.02.2003 - перестала работать интеграция.
В логе выдает следующее:
`2023-02-16 00:25:54.944 ERROR (MainThread) [custom_components.mosoblgaz] (user|xxxxxxxxxxxx)Error authenticating: Failed to authenticate: No CSRF token found
`
`2023-02-16 00:25:55.001 ERROR (MainThread) [custom_components.mosoblgaz.api] Error fetching X-SYSTEM-AUTH token: [Errno 1] [SSL: APPLICATION_DATA_AFTER_CLOSE_NOTIFY] application data after close notify (_ssl.c:2672)
`
Перезагрузка интеграции не помогает. При удалении и повторной настройке при указании логина и пароля сообщает ошибку.
При указании логина и пароля в configuration.yaml  в логе выдает то же смамое (см.выше).
Дополнительно - при ручном входе в ЛК Мособлгаза через браузер замечено, что теперь на сайте стоит проверка, требующая подтверждения типа "я человек". Возможно, проблема связана с этим.

**Comment by SandDeath** [comment]
Подтверждаю проблему, можем ли мы увидеть решение?

**Comment by booroondook-eng** [comment]
Сегодня (16.02.2023) с утра обнаружилось, что проблема исчезла.
